name = "msp430test"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["msp430test"]

[[depends-on]]
gnat_msp430_elf = "^12.2.0"
bare_runtime = "~0.1.0"
gnatprove = "^12.1.1"

[[pins]]
bare_runtime = { url='https://github.com/JeremyGrosser/bare_runtime#12.2' }

[gpr-set-externals]
BARE_RUNTIME_SWITCHES = "-mcpu=msp430xv2 -mhwmult=f5series"

[build-switches]
release.optimization = ["-Os", "-gnatn", "-gnatp"]
development.optimization = ["-O0", "-g"]

[build-profiles]
"*" = "release"

[[actions]]
type = "post-build"
command = ["gnatprove", "--quiet", "-P", "msp430test.gpr"]
